#!/bin/bash

# speedtest-easy (c) 2016 Craig Robert Wright <crw@crw.xyz>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# speedtest: a cron script for running the speedtest-cli on an hourly basis.
#
# This script could conceivably be run daily or more frequently, however
# the web ui is designed to process hourly data.
#
# The following values are set in /etc/environment, configurable via Docker env:
#     DB_FILENAME: location of the sqlite file
#     LOG_FILENAME: location of the log file
#     KEEP_LOG: determines if we keep the log file after conversion to sqlite.


echo "-----Start: `date -u -Iseconds`" >> $LOG_FILENAME
speedtest-cli >> $LOG_FILENAME
echo "-----End: `date -u -Iseconds`" >> $LOG_FILENAME

cd /speedtest-easy/convert/ && python speedtest-convert.py $DB_FILENAME $LOG_FILENAME

if [ $KEEP_LOG -eq 0 ]
then
	rm $LOG_FILENAME
fi
